import Head from "next/head";
import SmallCard from "@/components/molecules/SmallCard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Start my business card project here.</h1>
        <SmallCard
          name="Laura Smith"
          job="frontend developer"
          website="laurasmith.website"
        />
        <SmallCard
          name="Laura Smith"
          job="frontend developer"
          website="laurasmith.website"
        />
        <SmallCard
          name="Laura Smith"
          job="frontend developer"
          website="laurasmith.website"
        />
      </main>
    </>
  );
}
